title: Connell McCarthy
email: me@connellmccarthy.com
description: >- # this means to ignore newlines until "baseurl:"
  A multi-faceted Canadian Creative with a passion for 
  finding the blend between aesthetic and functionality.
url: "https://ssunmee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: ssunmee
permalink: pretty
image_path: /assets/articles/
repository: ssunmee/ssunmee.github.io
sass:
  sass_dir: _sass
  style: compressed
collections:
  article:
    output: true
    sort_by: date
    permalink: "/:collection/:path/"
    future: true
  collections:
    output: true
    sort_by: title
    permalink: "/prints/:collection/:path/"
  products:
    output: true
    sort_by: title
    permalink: "/prints/:collection/:path/"
