title: Haena Ryu
email: haena34@gmail.com
description: >-
  연세대학교 커뮤니케이션대학원 석사 2학기 유해나입니다.  
  커뮤니케이션 디자인을 전공하며 UXUI디자이너로 발전하고 있습니다.
  매일 뜨는 해처럼, 익숙하지만 꼭 필요한 존재로서  
  꾸준히 사람들에게 밝은 빛과 도움을 전할 수 있는 디자이너가 되고 싶습니다.
url: "https://ssunmee.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: ssunmee
permalink: pretty
image_path: /assets/articles/
repository: ssunmee/ssunmee.github.io
sass:
  sass_dir: _sass
  style: compressed
collections:
  article:
    output: true
    sort_by: date
    permalink: "/:collection/:path/"
    future: true
  collections:
    output: true
    sort_by: title
    permalink: "/prints/:collection/:path/"
  products:
    output: true
    sort_by: title
    permalink: "/prints/:collection/:path/"
